#!/bin/bash

JAVAOPTIONS=-Djava.security.auth.login.config=.\auth.conf

MAINCLASS="nl.planon.heracles.client.application.UpgradeTool"

MODE=-upgradeAll

java -cp "Apollo.jar;Aspose.Words.jar;EWS.jar;FacilityOffice.jar;Hades.jar;Hecate.jar;Heracles.jar;XmlSchema-1.4.7.jar;Zeus.jar;ant-launcher.jar;ant.jar;antlr-2.7.7.jar;axiom-api-1.2.12.jar;axiom-impl-1.2.12.jar;axis2-adb-1.6.1.jar;axis2-kernel-1.6.1.jar;axis2-transport-http-1.6.1.jar;axis2-transport-local-1.6.1.jar;axis2-transport-tcp-1.0.0.jar;axis2-xmlbeans-1.6.1.jar;batik-anim.jar;batik-awt-util.jar;batik-bridge.jar;batik-css.jar;batik-dom.jar;batik-ext.jar;batik-gvt.jar;batik-jviews-svggen.jar;batik-jviews-tiff.jar;batik-parser.jar;batik-script.jar;batik-svg-dom.jar;batik-svggen.jar;batik-transcoder.jar;batik-util.jar;batik-xml.jar;commons-beanutils-1.8.0.jar;commons-codec-1.3.jar;commons-collections-2.1.1.jar;commons-digester-2.1.jar;commons-httpclient-3.1.jar;commons-javaflow-20060411.jar;commons-logging-1.1.1.jar;configuration_client.jar;dom4j-1.6.1.jar;htmlcleaner2_0.jar;httpcore-4.0.jar;icu4j.jar;itext-2.1.7.jar;jackrabbit-jcr-commons-1.5.0.jar;jackrabbit-webdav-1.5.0.jar;jasperreports-javaflow-5.0.1.jar;jboss-common-core.jar;jboss-ejb-api_3.1_spec.jar;jboss-ejb3-ext-api.jar;jboss-j2se.jar;jboss-jms-api_1.1_spec.jar;jboss-jmx-mc-int.jar;jboss-kernel.jar;jboss-vfs.jar;jbossall-client-1.1.0.jar;jbosssx-client.jar;jbosssx-server.jar;jbosssx.jar;jcommon-1.0.15.jar;jdom-1.0.jar;jdt-compiler-3.1.1.jar;jfreechart-1.0.12.jar;jna-3.5.0.jar;jviews-chart-all.jar;jviews-diagrammer-all.jar;jviews-framework-all.jar;jviews-gantt-all.jar;jxl-2.6.10.jar;log4j-1.2.15.jar;mail-1.4.jar;mail.jar;neethi-3.0.1.jar;org.apache.felix.dependencymanager-3.0.0.jar;org.apache.felix.main-4.0.3.jar;org.osgi.compendium-4.2.0.jar;orviewer50-14.0.0.21.jar;planon-jboss-extensions-1.1.0.jar;platform-3.5.0.jar;pnkerberoswindowsnative-1.0.0.jar;pnlogging.jar;pnwebdavutil-3.0.7.jar;poi-3.7-20101029.jar;poi-ooxml-3.7-20101029.jar;poi-ooxml-schemas-3.7-20101029.jar;slf4j-api-1.5.0.jar;slf4j-log4j12-1.5.0.jar;tools.jar;vt-password-3.1.jar;waffle-jna-1.5.jar;wsdl4j-1.6.2.jar;xbean.jar;xml-apis-ext.jar;xml-apis.jar" %JAVAOPTIONS% %MAINCLASS% %MODE% > %1

